package ktorApiExample.core.application.usecases.findUserById

import ktorApiExample.core.application.seedwork.Usecase

interface FindUserByIdUsecase: Usecase<FindUserByIdUsecaseRequest, FindUserByIdUsecaseResponse>